#!/bin/bash

status(){
    echo "Total jobs: $(expr $(qstat -u $USER | wc -l) - 5)"
    echo "Running jobs: $(expr $(qstat -u $USER | grep ' R ' |wc -l))"
    echo "Queued jobs: $(expr $(qstat -u $USER | grep ' Q ' | wc -l))"
    qstat -u $USER
}

status
